// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNkHvx9gtvXV08_rRpnNqFWmG1-Km86l0',
    appId: '1:261972943390:web:93b7b835f8e73f8923c40f',
    messagingSenderId: '261972943390',
    projectId: 'srishtiauth',
    authDomain: 'srishtiauth.firebaseapp.com',
    storageBucket: 'srishtiauth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBx82WJHZMwJ6Xpwc46UtsU3Z-dn0YDyyA',
    appId: '1:261972943390:android:2cd15d91737331d623c40f',
    messagingSenderId: '261972943390',
    projectId: 'srishtiauth',
    storageBucket: 'srishtiauth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFo3ReSIRoSOe9EpvUm0bim9AeB6B7Sf4',
    appId: '1:261972943390:ios:adcd99b2b9606e1f23c40f',
    messagingSenderId: '261972943390',
    projectId: 'srishtiauth',
    storageBucket: 'srishtiauth.firebasestorage.app',
    iosBundleId: 'com.example.w3dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFo3ReSIRoSOe9EpvUm0bim9AeB6B7Sf4',
    appId: '1:261972943390:ios:adcd99b2b9606e1f23c40f',
    messagingSenderId: '261972943390',
    projectId: 'srishtiauth',
    storageBucket: 'srishtiauth.firebasestorage.app',
    iosBundleId: 'com.example.w3dev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNkHvx9gtvXV08_rRpnNqFWmG1-Km86l0',
    appId: '1:261972943390:web:f8bef650460adb7d23c40f',
    messagingSenderId: '261972943390',
    projectId: 'srishtiauth',
    authDomain: 'srishtiauth.firebaseapp.com',
    storageBucket: 'srishtiauth.firebasestorage.app',
  );
}
